name: GodOfWealth
main: com.mcstaralliance.godofwealth.GodOfWealth
version: '${project.version}'
depend:
  - Vault
  - PlaceHolderAPI
softdepend: [ PlayerPoints ]
commands:
  gow:
permissions:
  gow.panel:
    default: true
  gow.set:
    default: op
  gow.reload:
    default: op
