name: GodOfWealth
version: '${project.version}'
depend: [Vault]
softdepend: [PlayerPoints]
main: com.mcstaralliance.godofwealth.GodOfWealth
commands:
  gow:
permissions:
  gow.panel:
    default: true
  gow.set-player:
    default: op
  gow.reload:
    default: op
